export const FETCH_COORDINATES_REQUEST = "FETCH_COORDINATES_REQUEST";
export const FETCH_COORDINATES_SUCCESS = "FETCH_COORDINATES_SUCCESS";
export const FETCH_COORDINATES_FAILURE = "FETCH_COORDINATES_FAILURE";
